.PHONY: clean All

All:
	@echo "----------Building project:[ fibc - Debug ]----------"
	@cd "fibc" && "$(MAKE)" -f  "fibc.mk"
clean:
	@echo "----------Cleaning project:[ fibc - Debug ]----------"
	@cd "fibc" && "$(MAKE)" -f  "fibc.mk" clean
